name: Backend CI

on:
  push:
    branches: [ main, 'feature/**', 'release/**' ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run TypeScript build
        working-directory: backend
        run: npm run build

      - name: Run backend tests
        working-directory: backend
        run: |
          if npm test --silent; then echo "Tests passed"; else echo "Tests failed"; exit 1; fi

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist
