name: Backend CI

on:
  push:
    branches: [ main, 'feature/**', 'release/**' ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  build-and-test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run TypeScript build
        working-directory: backend
        run: npm run build

      - name: Run backend tests
        working-directory: backend
        run: |
          if npm test --silent; then echo "Tests passed"; else echo "Tests failed"; exit 1; fi

      - name: Audit dependencies (npm audit)
        working-directory: backend
        run: |
          echo "Running npm audit (report saved to audit.json)"
          npm audit --json > audit.json || true
        continue-on-error: false

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: backend/audit.json

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v4
