name: Backend Deploy (Vercel)

on:
  push:
    branches: [ main, 'release/**' ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

permissions:
  contents: read
  id-token: write

jobs:
  preview-and-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Build
        working-directory: backend
        run: npm run vercel-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

      - name: Deploy to Vercel (preview or prod)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          # For PRs or feature branches we deploy a preview; for main/releases we deploy to production.
          if [ -z "$VERCEL_TOKEN" ] || [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "Vercel secrets missing — skipping deploy";
            exit 0;
          fi
          cd backend
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "Deploying to production..."
            vercel --prod --yes --token $VERCEL_TOKEN
          else
            echo "Deploying preview..."
            vercel --confirm --token $VERCEL_TOKEN --yes
          fi
