name: Backend Deploy (Vercel)

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  preview-and-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Build
        working-directory: backend
        run: npm run vercel-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

      - name: Install Vercel CLI and jq
        run: |
          # ensure jq is available for JSON parsing and install vercel CLI
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g vercel@28

      - name: Deploy to Vercel (preview or prod) and run smoke test
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          if [ -z "$VERCEL_TOKEN" ] || [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "Vercel secrets missing — skipping deploy and smoke test";
            exit 0;
          fi
          set -e
          # If a custom project id is provided but no org id, the Vercel CLI
          # will error. Fail-safe: skip deploy with an informative message so
          # the workflow doesn't attempt a deploy that will always fail.
          if [[ -n "$VERCEL_PROJECT_ID" && -z "$VERCEL_ORG_ID" ]]; then
            echo "VERCEL_PROJECT_ID is set but VERCEL_ORG_ID is missing. Skipping deploy to custom project.";
            exit 0;
          fi
          # Deploy from the backend folder explicitly. Use --cwd and --local-config to
          # make sure the Vercel CLI targets the correct project root (avoids "Root
          # Directory does not exist" errors when the Vercel project is configured
          # with a subdirectory).
          VERCEL_CLI_OPTS=(--cwd backend --local-config backend/vercel.json --token "$VERCEL_TOKEN" --yes)
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "Deploying to production..."
            out=$(vercel --prod "${VERCEL_CLI_OPTS[@]}" 2>&1 || true)
          else
            echo "Deploying preview..."
            out=$(vercel "${VERCEL_CLI_OPTS[@]}" 2>&1 || true)
          fi
          echo "vercel output:"
          echo "$out"

          # Try to extract a vercel.app / vercel.pub URL from the output
          url=$(echo "$out" | grep -Eo 'https?://[a-zA-Z0-9._-]+\.vercel\.app' | head -n1 || true)
          if [ -z "$url" ]; then
            url=$(echo "$out" | grep -Eo 'https?://[a-zA-Z0-9._-]+\.(vercel\.app|vercel\.pub)' | head -n1 || true)
          fi
          # If still no URL, try listing recent deployments via the Vercel CLI
          if [ -z "$url" ]; then
            echo "No URL found in deploy output; attempting to list recent deployments via Vercel CLI..."
            # Try both common list commands; prefer JSON output and parse with jq (installed earlier)
            deploy_list=$(vercel deployments list --limit 5 --json "${VERCEL_CLI_OPTS[@]}" 2>/dev/null || vercel ls --limit 5 --json "${VERCEL_CLI_OPTS[@]}" 2>/dev/null || true)
            if [ -n "$deploy_list" ]; then
              # Try multiple likely JSON shapes: .[0].url, .[0].name, .[0].meta.url
              parsed_url=$(echo "$deploy_list" | jq -r '.[0].url // .[0].meta.url // .[0].name // empty' 2>/dev/null || true)
              if [ -n "$parsed_url" ]; then
                # ensure it has https:// prefix
                if [[ "$parsed_url" =~ ^https?:// ]]; then
                  url="$parsed_url"
                else
                  url="https://$parsed_url"
                fi
                echo "Found URL from deployments list: $url"
              else
                echo "Could not parse URL from deployments list output.";
              fi
            else
              echo "vercel deployments list returned no output or failed.";
            fi
          fi
          if [ -z "$url" ]; then
            echo "No URL available after fallback. Skipping smoke test.";
            exit 0;
          fi

          # Expose the deployed URL as a workflow output for easier follow-up checks
          echo "deploy_url=$url" >> "$GITHUB_OUTPUT"

          echo "Running smoke test against: $url/mfarmacias/debug/ping"
          # Give the deployment a few seconds to finish
          sleep 5
          # perform a GET, capture status and body
          PING_BODY=$(curl -sS "$url/mfarmacias/debug/ping" || true)
          PING_STATUS=$(echo "$PING_BODY" | { http_code=$(curl -s -o /dev/null -w "%{http_code}" "$url/mfarmacias/debug/ping" || echo "000"); echo "$http_code"; } )
          echo "Deployed: $url"
          echo "Smoke test status: $PING_STATUS"
          echo "Smoke test body: $PING_BODY"

          # expose ping results as outputs as well
          echo "ping_status=$PING_STATUS" >> "$GITHUB_OUTPUT"
          # sanitize newlines in body for output
          safe_body=$(echo "$PING_BODY" | tr '\n' ' ' | sed 's/\r//g')
          echo "ping_body=$safe_body" >> "$GITHUB_OUTPUT"
          # fail the job if ping not 200
          if [[ "$PING_STATUS" != "200" ]]; then
            echo "Smoke test failed (status $PING_STATUS)";
            exit 1;
          fi
