name: Flutter tests

on:
  push:
    branches: [ main ]
    paths:
      - 'mobile/**'
      - 'pubspec.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mobile/**'
      - 'pubspec.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Pin to a concrete Flutter version that includes Dart >= 3.1 so
          # dependency resolution is reproducible across CI runs.
          flutter-version: '3.13.0'
      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            mobile/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get
      - name: Run tests
        run: |
          cd mobile
          flutter test -r expanded
