name: Mobile CI

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get
      - name: Run tests
        run: |
          cd mobile
          flutter test --coverage
      - name: Build APK (unsigned)
        env:
          API_BASE_URL: ${{ secrets.PROD_API_BASE_URL }}
        run: |
          cd mobile
          flutter build apk --release --dart-define=API_BASE_URL=${{ secrets.PROD_API_BASE_URL }}
